# Generated by Django 5.1.3 on 2024-11-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_folder_deleted_at_folder_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='name',
            new_name='original_name',
        ),
    ]
